modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"
issueTrackerURL="https://github.com/SleepyTrousers/EnderIO"

[[mods]]
modId="enderiointegrationtic"
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Integration with Thaumcraft"
displayURL="Ender IO Integration with Tinkers' Construct"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, EpicSquid, rezonant"
displayTest="MATCH_VERSION"
description="I'm melting!"

[[dependencies.enderiointegrationtic]]
    modId="enderio"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"

[[mods]]
modId="enderiointegrationticlate"
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Integration with Thaumcraft"
displayURL="Ender IO Integration with Tinkers' Construct"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, EpicSquid, rezonant"
displayTest="MATCH_VERSION"
description="I'm melting!"

[[dependencies.enderiointegrationticlate]]
    modId="enderio"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"
