modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"
issueTrackerURL="https://github.com/SleepyTrousers/EnderIO"

[[mods]]
modId="enderiorefinedstorageconduits"
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Refined Storage Conduits"
displayURL="https://enderio.com/"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, EpicSquid, rezonant"
displayTest="MATCH_VERSION"
description="EnderIO conduits for Refined Storage cabling"

[[dependencies.enderiorefinedstorageconduits]]
    modId="enderioconduits"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"
