modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"
issueTrackerURL="https://github.com/SleepyTrousers/EnderIO"

[[mods]]
modId="enderiointegrationforestry"
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Integration with Forestry"
displayURL="https://enderio.com/"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, EpicSquid, bdew, mezz, rezonant"
displayTest="MATCH_VERSION"
description="I'm growing!"

[[dependencies.enderiointegrationforestry]]
    modId="enderio"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"
