modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"
issueTrackerURL="https://github.com/SleepyTrousers/EnderIO"

[[mods]]
modId="enderio"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO"
displayURL="https://enderio.com/"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, rezonant"
displayTest="MATCH_VERSION"
description="Compact conduits, painted things and all sorts of stuff and bling."

[[mods]]
modId="enderiobase"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Base"
displayURL="https://enderio.com/"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, rezonant"
displayTest="MATCH_VERSION"
description="Basic materials and items for all EnderIO modules."

[[dependencies.enderiobase]]
    modId="enderio"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"

