modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"
issueTrackerURL="https://github.com/SleepyTrousers/EnderIO"

[[mods]]
modId="enderiointegrationthaumcraft"
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Integration with Thaumcraft"
displayURL="https://enderio.com/"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, EpicSquid, rezonant"
displayTest="MATCH_VERSION"
description="I'm a wizard, Henry!"

[[dependencies.enderiointegrationthaumcraft]]
    modId="enderio"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"
