modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"
issueTrackerURL="https://github.com/SleepyTrousers/EnderIO"

[[mods]]
modId="enderioconduits"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Conduits"
displayURL="https://enderio.com/"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, HypherionSA, rezonant"
displayTest="MATCH_VERSION"
description="Compact conduits."

[[mods]]
modId="enderiopowertools"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Powertools"
displayURL="https://enderio.com/"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, rezonant"
displayTest="MATCH_VERSION"
description="Capacitor Bank and Power Monitor."

[[dependencies.enderioconduits]]
    modId="enderio"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"


[[dependencies.enderiopowertools]]
    modId="enderio"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.enderiopowertools]]
    modId="enderioconduits"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"