modLoader="javafml"
loaderVersion="[43,)"
license="Public Domain"
issueTrackerURL="https://github.com/SleepyTrousers/EnderIO"

[[mods]]
modId="enderiomachines"
credits="By CrazyPants, with the help of many"
version="${file.jarVersion}"
displayName="Ender IO Machines"
displayURL="https://enderio.com/"
logoFile="enderio.png"
authors="CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, rezonant"
displayTest="MATCH_VERSION"
description="Everything that goes krrrrkrrr and shtshtshtsht and kagrmkagrmkaguddr."

[[dependencies.enderiomachines]]
    modId="enderio"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"
